MandarinMedien\MMCmfContentBundle\Entity\Page:
    type: entity
    table: null
    fields:
        metaTitle:
            type: string
            length: 255
            nullable: true
        metaKeywords:
            type: string
            length: 255
            nullable: true
        metaDescription:
            type: text
            nullable: true
        metaRobots:
            type: string
            length: 255
            nullable: true
        metaAuthor:
            type: string
            length: 255
            nullable: true
        metaImage:
            type: string
            length: 255
            nullable: true

        template:
            type: string
            nullable: true


    manyToMany:
        routes:
            targetEntity: MandarinMedien\MMCmfRoutingBundle\Entity\NodeRoute
            joinTable:
                name: page_routes
                joinColumns:
                  node_id:
                    referencedColumnName: id
                    onDelete: cascade
                inverseJoinColumns:
                  route_id:
                    referencedColumnName: id
                    unique: true
                    onDelete: cascade
            cascade:
                - all


    lifecycleCallbacks: {  }
