mm_cmf_content:

    page_nodes:
        MandarinMedien\MMCmfContentBundle\Entity\Page:
            templates:
                - { name: 'default', template: 'MMCmfContentBundle:cmf:Page/default.html.twig' }

    content_nodes:

        MandarinMedien\MMCmfContentBundle\Entity\ContentNode:
            hiddenFields:
                - "attributes"
            templates:
              - { name: 'default', template: "MMCmfContentBundle:cmf:contentNode/contentNode_default.html.twig" }

        MandarinMedien\MMCmfContentBundle\Entity\RowContentNode:
            icon: 'fa fa-th-list'
            hiddenFields:
                  - "attributes"
            templates:
              - { name: 'default', template: "MMCmfContentBundle:cmf:rowContentNode/rowContentNode_default.html.twig" }

        MandarinMedien\MMCmfContentBundle\Entity\ParagraphContentNode:
            icon: 'fa fa-paragraph'
            templates:
                - { name: 'default', template: "MMCmfContentBundle:cmf:paragraphContentNode/paragraphContentNode_default.html.twig" }
                - { name: 'Upside-Down', template: "MMCmfContentBundle:cmf:paragraphContentNode/paragraphContentNode_upside_down.html.twig" }
            hiddenFields:
                - "attributes"
                #- "headline"
                #- "text"

        MandarinMedien\MMCmfContentBundle\Entity\ContainerContentNode:
            icon: 'fa fa-folder-o'
            simpleForm:
                type: 'MandarinMedien\MMCmfContentBundle\Form\ContainerContentNodeType'
                template: "MMCmfContentBundle:Form:container_form.html.twig"
            hiddenFields:
                - "attributes"
twig:
    form:
        resources:
            - MMCmfContentBundle:Form:nodetree.html.twig

assetic:
    assets:
        mm_cmf_content_assets_js:
            inputs:
              - '@MMCmfContentBundle/Resources/public/js/summernote/summernote.js'
              - '@MMCmfContentBundle/Resources/public/vendor/dragula.js/dist/dragula.min.js'

              #cmfFieldPlugins
              - "@MMCmfContentBundle/Resources/public/js/cmfField/mmCmfFieldString.js"
              - "@MMCmfContentBundle/Resources/public/js/cmfField/mmCmfFieldWYSIWYG.js"

              - "@MMCmfContentBundle/Resources/public/js/mmCmfContentEditor.js"
              - "@MMCmfContentBundle/Resources/public/js/mmCmfContentFieldEditor.js"
              - "@MMCmfContentBundle/Resources/public/js/mmCmfContentStructureEditor.js"
              - "@MMCmfContentBundle/Resources/public/js/mmCmfContentActionBar.js"
              - "@MMCmfContentBundle/Resources/public/js/core.js"

              #formType Types
              - '@MMCmfContentBundle/Resources/public/js/form/HTMLType.js'
              - '@MMCmfContentBundle/Resources/public/js/form/NodeTreeType.js'
              - '@MMCmfContentBundle/Resources/public/js/form/MenuType.js'
              - '@MMCmfContentBundle/Resources/public/js/form/FormHandler.js'

        mm_cmf_content_summernote_assets_css:
            filters:
                - 'cssrewrite'
            inputs:
                - 'bundles/mmcmfcontent/vendor/summernote/dist/summernote.css'
#               - '//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css'
#               - '//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css'

#        mm_cmf_content_summernote_assets_js:
#            filters: ~
#            inputs:
#
#                #- '//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js'
#                #- '//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js'
#                #- '//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js'

        mm_cmf_content_assets_css:
            filters:
                - 'less'
            inputs:
                - "@MMCmfContentBundle/Resources/public/css/mmCmfContentEditor.less"
                - '@MMCmfContentBundle/Resources/public/vendor/dragula.js/dist/dragula.min.css'
                - '@mm_cmf_content_summernote_assets_css'
