mm_cmf_content_save:
    path:     /save
    defaults: { _controller: MMCmfContentBundle:ContentNode:save}
    condition: "request.isXmlHttpRequest()"
    requirements:
        _format: json
        _method: POST

mm_cmf_content_node_form:
    path:     /{id}/edit
    defaults: { _controller: MMCmfContentBundle:ContentNode:getForm}

mm_cmf_content_node_update:
    path: /{id}/update
    defaults:  { _controller: MMCmfContentBundle:ContentNode:update}


mm_cmf_content_node_select:
    path: /discrimators
    defaults:  { _controller: MMCmfContentBundle:ContentNode:getDiscrimatorsModal}
