mm_cmf_content_save:
    path:     /save
    defaults: { _controller: MMCmfContentBundle:ContentNode:save}
    condition: "request.isXmlHttpRequest()"
    requirements:
        _format: json
        _method: POST
