<?php

namespace MandarinMedien\MMCmfContentBundle\Entity;

/**
 * ContentNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
